#################################################################################
# Eclipse Tractus-X - Tractus-X TestLab
#
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

"""CLI command for generating the step reference pages from the step contracts."""

from __future__ import annotations

import json
from pathlib import Path

import typer

from tractusx_testlab.authoring.registry import StepRegistry
from tractusx_testlab.authoring.step_catalog import render_catalog
from tractusx_testlab.authoring.step_pages import render_nav, render_pages
from tractusx_testlab.cli import app

_DOCS_DIR = Path("docs")
_DEFAULT_OUTPUT = _DOCS_DIR / "api-reference" / "steps"
_MKDOCS = Path("mkdocs.yml")

#: The lines of ``mkdocs.yml`` the step reference's nav entries are kept between.
NAV_BEGIN = "# >>> step reference nav, generated by `testlab docs`"
NAV_END = "# <<< step reference nav"


@app.command("docs")
def docs(
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help=(
            f"Write the pages into this directory (default: {_DEFAULT_OUTPUT}, which also "
            f"updates the navigation in {_MKDOCS}). Use '-' to print one document to stdout."
        ),
    ),
    step: list[str] | None = typer.Option(
        None,
        "--step",
        "-s",
        help="Document only these step types. Repeatable. Defaults to all registered steps.",
    ),
    as_json: bool = typer.Option(
        False,
        "--json",
        help="Emit the raw contracts as JSON Schema instead of Markdown. Implies '-o -'.",
    ),
    check: bool = typer.Option(
        False,
        "--check",
        help="Exit non-zero if the pages on disk differ from what would be generated.",
    ),
) -> None:
    """Generate the step reference from the steps' declared input/output models."""

    if step:
        _reject_unknown_steps(step)

    if as_json or str(output) == "-":
        typer.echo(_as_json(step) if as_json else render_catalog(step), nl=False)
        return

    target = output or _DEFAULT_OUTPUT
    pages = render_pages(step)
    manages_nav = target == _DEFAULT_OUTPUT and _MKDOCS.exists()
    mkdocs = _with_nav(step, target) if manages_nav else None

    if check:
        _check_up_to_date(target, pages, mkdocs)
        return

    _write_pages(target, pages)
    if mkdocs is not None:
        _MKDOCS.write_text(mkdocs, encoding="utf-8")
    typer.echo(f"Wrote {len(pages)} pages to {target}")


def _reject_unknown_steps(step_types: list[str]) -> None:
    unknown = sorted(set(step_types) - set(StepRegistry.list_step_types()))
    if unknown:
        typer.echo(f"Error: unknown step type(s): {', '.join(unknown)}", err=True)
        raise typer.Exit(1)


def _as_json(step_types: list[str] | None) -> str:
    """Render every step's contract as a JSON Schema document."""
    names = sorted(step_types or StepRegistry.list_step_types())
    contracts = []
    for name in names:
        step_cls = StepRegistry.get_any(name)
        if step_cls is not None:
            contracts.append(step_cls.describe().model_dump(exclude_none=True))
    return json.dumps(contracts, indent=2) + "\n"


def _on_disk(target: Path) -> dict[str, str]:
    if not target.is_dir():
        return {}
    return {
        path.relative_to(target).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(target.rglob("*.md"))
    }


def _write_pages(target: Path, pages: dict[str, str]) -> None:
    """Write *pages* into *target*, removing pages that are no longer generated."""
    for stale in set(_on_disk(target)) - set(pages):
        (target / stale).unlink()
    for relative, content in pages.items():
        path = target / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    for directory in sorted(target.rglob("*"), reverse=True):
        if directory.is_dir() and not any(directory.iterdir()):
            directory.rmdir()


def _with_nav(step_types: list[str] | None, target: Path) -> str:
    """``mkdocs.yml`` with the generated nav entries between the markers."""
    text = _MKDOCS.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    begin = next((i for i, line in enumerate(lines) if line.strip() == NAV_BEGIN), None)
    end = next((i for i, line in enumerate(lines) if line.strip() == NAV_END), None)
    if begin is None or end is None or end < begin:
        typer.echo(
            f"Error: {_MKDOCS} has no '{NAV_BEGIN}' ... '{NAV_END}' block to write the "
            "step reference navigation into.",
            err=True,
        )
        raise typer.Exit(1)
    indent = lines[begin][: len(lines[begin]) - len(lines[begin].lstrip())]
    root = target.relative_to(_DOCS_DIR).as_posix()
    nav = [f"{indent}{entry}\n" for entry in render_nav(step_types, root=root)]
    return "".join([*lines[: begin + 1], *nav, *lines[end:]])


def _check_up_to_date(target: Path, pages: dict[str, str], mkdocs: str | None) -> None:
    """Fail when the committed pages or navigation no longer match the code."""
    on_disk = _on_disk(target)
    stale = sorted(
        relative
        for relative in set(on_disk) | set(pages)
        if on_disk.get(relative) != pages.get(relative)
    )
    if mkdocs is not None and _MKDOCS.read_text(encoding="utf-8") != mkdocs:
        stale.append(str(_MKDOCS))
    if stale:
        typer.echo(
            f"Error: {target} is out of date ({', '.join(stale)}); run 'testlab docs'.",
            err=True,
        )
        raise typer.Exit(1)
    typer.echo(f"{target} is up to date")
